alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: protokollab.com
  type: PRIMARY
- domain: help.protokollab.com
  type: ALIAS
envs:
- key: MONGODB_URI
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:XAoLjZeAA6Kp1UVGqnVXjOVxPFVKEqMb:p1Dyb0nxaaoQGwzC9Gi//l2E18vebtSpXvs8bQ6G8sOfQ8GL7l8cjQtvToS9zToIRXVoO557+jhXuCPo8VKj07Tsbm9RbtaYIPQuGXW1mDfWWPzIPWpuVqZXLGoqn4rsO36q6jco5gzYxNpaESJCZCR/eLV+AMsP]
- key: JWT_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:Qqguzydch7qLoMQfCCBXPR9bEFIIbP3E:nEvrCMEPGy6tiAP+nbnuBHiryNJULzGXlXp+pSP5824AypboZLyFLU+8yUa25kBG6EW78sFy+6IkMrwcekGLdbcI9WdZ0iwS49aJUGtX1JQ=]
- key: GEMINI_API_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:PJzTJ8MQrvppNjdto3XYFPl7No2c2sm4:Wm9+VFpIpdnRnCAK+Ew1sFX5MQOFBB9Tqa59r1Q4E/VpxA5kVyeLQijfUjFllqOKWKq01JW8Lw==]
- key: USDA_FDC_API_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:ewc8Dh5VIFbaDwxwpMqMJ5cQjh1+SJmt:ZB1IHJ4480ThM705IP1eW5bRy20BFK4matyjm6KWq6NHkkeKRxw0CghpULFKul/MngG2mLe3HBY=]
- key: SENDGRID_API_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:MJh4uYDFwXnHU9FB8F72fbCEYWr60k/M:X3TMZd35HN/oT3O/h8/AclmFRd7Il2PjYC0K9Y8RM1d428k7CjsXbvPYRV6qEsK5pNzLlniGwZBJQY7PXJzW5+72DZBPRg5FrDT7dxfPLDiJdZdMuw==]
- key: SENDGRID_FROM_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: jeff@mail.protokollab.com
- key: SENDGRID_FROM_NAME
  scope: RUN_AND_BUILD_TIME
  value: Jeff Jassky
- key: SUPPORT_ADMIN_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: jeff@jeffjassky.com
- key: TRUST_PROXY
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: COOKIE_SAMESITE
  scope: RUN_AND_BUILD_TIME
  value: lax
- key: VAPID_PUBLIC_KEY
  scope: RUN_AND_BUILD_TIME
  value: BKd14uk08QMXBafYw4qJ2yjMLtF1gB_xolrbBFVR6sRK1SvESU7MS98gh4MBpqAQNsnPLtSTpkIXEoqXACbR6u4
- key: VAPID_PRIVATE_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:I4qPFoVU/4MncPBdS+fy20xWRAo6omyu:DNwyMlcRM8ndbi+zjdnRvpEHK6Ny7QCli5a4WUhOH3kWATrj9RLUMoHASdWrddk6Nq1KShjkpJYKkO4=]
- key: VAPID_SUBJECT
  scope: RUN_AND_BUILD_TIME
  value: mailto:jeff@jeffjassky.com
- key: S3_ENDPOINT
  scope: RUN_AND_BUILD_TIME
  value: https://nyc3.digitaloceanspaces.com
- key: S3_REGION
  scope: RUN_AND_BUILD_TIME
  value: nyc3
- key: S3_BUCKET
  scope: RUN_AND_BUILD_TIME
  value: protokol-lab
- key: S3_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:ib0eB+slvsDxiBmnMUIUVIibUP3XiL+0:Zo6rxH57BUSfzr0vCIodF0kxkXP9ujWUu/bMTP/MI0juqxsp]
- key: S3_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:4H6w7YRnax/Ehn4w6SK3+8BSbtLSHKIn:QwBMU016FsGXbFEdHPO42/amX8s3rsuMUcr74+O5reJLgapo5D/3u1I37lT6yQAVdRdFY8Qt2FzOyRE=]
- key: S3_PRESIGN_TTL
  scope: RUN_AND_BUILD_TIME
  value: "1800"
- key: STRIPE_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:ZHCA7UZxFQw2Po2kE4WBV4JU5FkgKKfH:wQWIpXoOZIk+Eblun+RQHavyHvEA5zWenbdH0rTZLQGcgpblk7jdiuElAudh4F5LzAVDAZq1EWnM/U8NpxnC+0PijgUBI6xh2HZ7pWgGcDaUK0CTAoCWDAdFeyyx2ikTBarvxRVqIi/u4jihCRKQS9G9rFpHPZNHnQRQ]
- key: STRIPE_WEBHOOK_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:dZSCq1kpGK+b1pjI15uyd4Eo8E1TKo4e:PjN35URlFtl32zl3drg/4UKsJUpPWWBg3ivv12rykifzHmSow39aEdyIbW5C5eqDKLt0XNUVY3yJCxWtLiUPqjMe/DMAMkYWkc10xeURiL0lWGX6TcY=]
- key: GOOGLE_CLIENT_ID
  scope: RUN_AND_BUILD_TIME
  value: 14815036497-cqoci8uuamf9g8n5pq6mgrdiuaro7lf5.apps.googleusercontent.com
- key: VITE_GOOGLE_CLIENT_ID
  scope: RUN_AND_BUILD_TIME
  value: 14815036497-cqoci8uuamf9g8n5pq6mgrdiuaro7lf5.apps.googleusercontent.com
- key: MAILER_INTERNAL_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:UzI4b2OfxuXMs7bhxRc1TDXHtjHvKoiE:v1qn13NZEKyWY/6Cs+gr7xsCGxCC/ryDG99wqFFAifbzjg5KmlN9o9nHKIQwWQav4D4U07rbcHbcN+jhrn6isYaNWMiVwnG6KzpMy89+nHs=]
- key: MAILER_UNSUB_SECRET
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:ZHMQljam7la1b8daOFO25tmU5oEhMM9C:F9LzvGeSBDzsotnk/LVhR47W6IhQnOq/OA+A1sNuHfMH2E75Rmo4KRtRfgxYyo+MWGsVc8LI7797j1LeGCC5m5rK0SfAmK6zrxnVcZxIC4U=]
- key: SENDGRID_WEBHOOK_VERIFICATION_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:qQlPN6rlpR3iGfs+KGzT+ckx0AmV2tco:zGEP4XclKUiDBtehklQqPO1EYza9A8Cfbbwy6EW9PmjeeID17TSQRBXdTlsl0ItxVPvwg006UFarq3lWB2K8updPk9wqO43XcqCLgCeNcOIbuU4zcJyCfhVKgoAT9CyQA10MvaM8Lur/N2eFYWHsAm5WWq8kndPcje4HF0L0VuoqOxZMvjtlgpBa+xo=]
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: protokol-lab
    match:
      authority: {}
      path:
        prefix: /
name: protokol-lab
region: nyc
services:
- environment_slug: node-js
  github:
    branch: main
    repo: JeffJassky/protokol-lab
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: protokol-lab
  source_dir: /
