import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import mongoose from 'mongoose';
import authRoutes from './routes/auth.js';
import settingsRoutes from './routes/settings.js';
import weightRoutes from './routes/weight.js';
import foodRoutes from './routes/food.js';
import foodlogRoutes from './routes/foodlog.js';
import mealsRoutes from './routes/meals.js';
import symptomsRoutes from './routes/symptoms.js';
import waistRoutes from './routes/waist.js';
import doseRoutes from './routes/doses.js';
import compoundsRoutes from './routes/compounds.js';
import chatRoutes from './routes/chat.js';
import notesRoutes from './routes/notes.js';
import photosRoutes from './routes/photos.js';
import pushRoutes, { publicPushRouter } from './routes/push.js';
import stripeRoutes, { publicStripeRouter } from './routes/stripe.js';
import adminRoutes from './routes/admin.js';
import supportRoutes from './routes/support.js';
import adminSupportRoutes from './routes/adminSupport.js';
import { requireAuth } from './middleware/requireAuth.js';
import { requireAdmin } from './middleware/requireAdmin.js';
import { runStartupBackup } from './services/backup.js';
import { initPush } from './services/push.js';
import { startScheduler, stopScheduler } from './services/scheduler.js';
import { logger, httpLogger, childLogger, errContext } from './lib/logger.js';

const log = childLogger('boot');
const app = express();
const PORT = process.env.PORT || 3001;
const isProd = process.env.NODE_ENV === 'production';

app.set('trust proxy', Number(process.env.TRUST_PROXY ?? 1));

app.use(helmet());

const corsOrigin = isProd
  ? (process.env.APP_URL || false)
  : true;
app.use(cors({ origin: corsOrigin, credentials: true }));

// Stripe webhook must see the raw request body to verify the signature.
// Mounted at an exact path BEFORE express.json() so the global JSON parser
// doesn't consume the buffer. Other /api/stripe routes parse JSON normally.
app.use('/api/stripe/webhook', express.raw({ type: 'application/json' }), publicStripeRouter);

app.use(express.json());
app.use(cookieParser());

// Per-request logger w/ reqId. Must be before routes so req.log exists
// everywhere downstream. Exposes res header `x-request-id` for client tracing.
app.use(httpLogger);

// Mongo connection events — track drops/reconnects that would otherwise be
// silent and surface as mystery 500s.
mongoose.connection.on('disconnected', () => {
  childLogger('db').warn('mongoose disconnected');
});
mongoose.connection.on('reconnected', () => {
  childLogger('db').info('mongoose reconnected');
});
mongoose.connection.on('error', (err) => {
  childLogger('db').error(errContext(err), 'mongoose error');
});

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok' });
});

app.use('/api/auth', authRoutes);
app.use('/api/push', publicPushRouter);
app.use('/api/push', requireAuth, pushRoutes);

app.use('/api/settings', requireAuth, settingsRoutes);
app.use('/api/weight', requireAuth, weightRoutes);
app.use('/api/food', requireAuth, foodRoutes);
app.use('/api/foodlog', requireAuth, foodlogRoutes);
app.use('/api/meals', requireAuth, mealsRoutes);
app.use('/api/symptoms', requireAuth, symptomsRoutes);
app.use('/api/waist', requireAuth, waistRoutes);
app.use('/api/doses', requireAuth, doseRoutes);
app.use('/api/compounds', requireAuth, compoundsRoutes);
app.use('/api/chat', requireAuth, chatRoutes);
app.use('/api/notes', requireAuth, notesRoutes);
app.use('/api/photos', requireAuth, photosRoutes);
app.use('/api/stripe', requireAuth, stripeRoutes);
app.use('/api/support', requireAuth, supportRoutes);
app.use('/api/admin/support', requireAuth, requireAdmin, adminSupportRoutes);
app.use('/api/admin', requireAuth, requireAdmin, adminRoutes);

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const clientDist = path.resolve(__dirname, '../../client/dist');
// Prerendered marketing routes live in client/prerendered/ (tracked in git,
// generated by `npm run build:full` locally). The production build image on
// DigitalOcean can't run Puppeteer (missing Chromium system libs), so we
// bake these HTML files into the repo and the server reads them at runtime.
// This path is stable across deploys — dist/ gets wiped on each build.
const clientPrerendered = path.resolve(__dirname, '../../client/prerendered');

app.use(express.static(clientDist));

const SHELL_FILE = path.join(clientDist, 'index.html');

// Prerendered HTML is committed to git with whatever Vite hashes existed at
// the time of `npm run build:full` locally. Production rebuilds dist/ with
// fresh content hashes (Puppeteer can't run on the DO build image, so the
// prerender step is skipped there). If we serve the committed HTML as-is,
// it 404s on stale /assets/index-OLDHASH.{js,css} and the page renders
// unstyled. So at server start we read the live shell to learn the *current*
// asset filenames, and rewrite any matching paths in prerendered HTML on
// the way out.
let CURRENT_JS = null;
let CURRENT_CSS = null;
try {
  const shellHtml = fs.readFileSync(SHELL_FILE, 'utf8');
  CURRENT_JS = shellHtml.match(/<script[^>]+src="(\/assets\/index-[^"]+\.js)"/)?.[1] || null;
  CURRENT_CSS = shellHtml.match(/<link[^>]+href="(\/assets\/index-[^"]+\.css)"/)?.[1] || null;
  log.info({ js: CURRENT_JS, css: CURRENT_CSS }, 'resolved current dist asset paths for prerender rewrite');
} catch (err) {
  log.warn({ err: err.message }, 'could not read SHELL_FILE for prerender asset rewrite — prerendered routes may render unstyled');
}

function sendPrerendered(res, filepath) {
  if (!CURRENT_JS && !CURRENT_CSS) return res.sendFile(filepath);
  let html;
  try {
    html = fs.readFileSync(filepath, 'utf8');
  } catch {
    return res.sendFile(filepath);
  }
  if (CURRENT_JS) html = html.replace(/\/assets\/index-[A-Za-z0-9_-]+\.js/g, CURRENT_JS);
  if (CURRENT_CSS) html = html.replace(/\/assets\/index-[A-Za-z0-9_-]+\.css/g, CURRENT_CSS);
  res.type('html').send(html);
}

app.use((req, res, next) => {
  if (req.method !== 'GET' && req.method !== 'HEAD') return next();
  if (req.path.startsWith('/api/')) return next();

  // 1. Root "/" — look for prerendered home; fall back to SPA shell.
  if (req.path === '/') {
    const homePrerendered = path.join(clientPrerendered, 'index.html');
    if (fs.existsSync(homePrerendered)) return sendPrerendered(res, homePrerendered);
    return res.sendFile(SHELL_FILE);
  }

  // 2. Sub-routes ("/pricing", "/compare/shotsy") — look for matching
  //    prerendered HTML under client/prerendered/<path>/index.html.
  if (req.path.indexOf('.') === -1) {
    const prerendered = path.join(clientPrerendered, req.path, 'index.html');
    if (fs.existsSync(prerendered)) return sendPrerendered(res, prerendered);
  }

  // 3. Fall back to the SPA shell for auth, app, and unknown routes.
  res.sendFile(SHELL_FILE);
});

// Central error handler — logs full stack w/ correlation fields, returns
// generic 500 body so stack traces don't leak.
app.use((err, req, res, _next) => {
  const reqLog = req.log || log;
  reqLog.error(
    { ...errContext(err), method: req.method, path: req.path, userId: req.userId ? String(req.userId) : undefined },
    'unhandled route error',
  );
  if (res.headersSent) return;
  res.status(err.status || 500).json({ error: 'Internal server error' });
});

process.on('uncaughtException', (err) => {
  logger.fatal(errContext(err), 'uncaughtException — exiting');
  process.exit(1);
});
process.on('unhandledRejection', (err) => {
  logger.fatal(errContext(err), 'unhandledRejection — exiting');
  process.exit(1);
});

let server;
let shuttingDown = false;
const shutdown = async (signal) => {
  if (shuttingDown) return;
  shuttingDown = true;
  log.info({ signal }, 'shutdown requested');
  const forceExit = setTimeout(() => {
    log.error('graceful shutdown timed out — forcing exit');
    process.exit(1);
  }, 3000).unref();
  try {
    if (server) {
      log.debug('closing http server');
      await new Promise((resolve) => server.close(resolve));
    }
    log.debug('stopping scheduler');
    await stopScheduler();
    log.debug('disconnecting mongo');
    await mongoose.disconnect();
    log.info('shutdown complete');
  } catch (err) {
    log.error(errContext(err), 'error during shutdown');
  } finally {
    clearTimeout(forceExit);
    process.exit(0);
  }
};
process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

try {
  log.info({ port: PORT, env: process.env.NODE_ENV || 'development', logLevel: logger.level }, 'starting server');
  const connectStart = Date.now();
  await mongoose.connect(process.env.MONGODB_URI);
  log.info({ durationMs: Date.now() - connectStart }, 'mongo connected');

  runStartupBackup();
  initPush();
  await startScheduler();

  server = app.listen(PORT, () => {
    log.info({ port: PORT, url: `http://localhost:${PORT}` }, 'http listening');
  });
  server.on('error', (err) => {
    log.fatal(errContext(err), 'http server error');
    process.exit(1);
  });
} catch (err) {
  log.fatal(errContext(err), 'startup failed');
  process.exit(1);
}
